<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>18d6285e-9fef-4c59-aeb5-ac40d4bbf901</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.32" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ActionGenerator.Application\ActionGenerator.Application.csproj" />
    <ProjectReference Include="..\ActionGenerator.Infrastructure\ActionGenerator.Infrastructure.csproj" />
  </ItemGroup>

</Project>
