// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TWAction.Persistence;

#nullable disable

namespace TWAction.Persistence.Migrations
{
    [DbContext(typeof(TWActionDbContext))]
    [Migration("20260330201914_NobleBudget")]
    partial class NobleBudget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TWAction.Domain.AttackCommands.AttackCommandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DestinationPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationVillageId")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationX")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationY")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MaxArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MaxDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MinArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MinDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceVillageId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceX")
                        .HasColumnType("integer");

                    b.Property<int>("SourceY")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ScheduleId");

                    b.ToTable("AttackCommands", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.NobleBudgetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Budget")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId", "PlayerId")
                        .IsUnique();

                    b.ToTable("NobleBudgets", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.ScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Enemies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SentToPlemionaRozpiskiAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("World")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid");

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.TroopsStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompressedData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.ToTable("TroopsStates", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Settings.ReconnaissanceSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MaxArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxPopulationInSourceVillage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MinArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MinDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinDistanceToFront")
                        .HasColumnType("integer");

                    b.Property<int>("MinSpyCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SkipNightSendings")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.ToTable("ReconnaissanceSettings", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Provider")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Users.UserSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_UserSessions_ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.NobleBudgetEntity", b =>
                {
                    b.HasOne("TWAction.Domain.Schedules.ScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.ScheduleEntity", b =>
                {
                    b.HasOne("TWAction.Domain.Users.UserEntity", null)
                        .WithMany("Schedules")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.TroopsStateEntity", b =>
                {
                    b.HasOne("TWAction.Domain.Schedules.ScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.Settings.ReconnaissanceSettings", b =>
                {
                    b.HasOne("TWAction.Domain.Schedules.ScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.Users.UserSessionEntity", b =>
                {
                    b.HasOne("TWAction.Domain.Users.UserEntity", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.Users.UserEntity", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
