// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TWAction.Persistence;

#nullable disable

namespace TWAction.Persistence.Migrations
{
    [DbContext(typeof(TWActionDbContext))]
    partial class TWActionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TWAction.Domain.AttackCommands.AttackCommandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DestinationPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationVillageId")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationX")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationY")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MaxArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MaxDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MinArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MinDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceVillageId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceX")
                        .HasColumnType("integer");

                    b.Property<int>("SourceY")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ScheduleId");

                    b.ToTable("AttackCommands", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.NobleBudgetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Budget")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId", "PlayerId")
                        .IsUnique();

                    b.ToTable("NobleBudgets", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.ScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Enemies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SentToPlemionaRozpiskiAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("World")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid");

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.TroopsStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompressedData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.ToTable("TroopsStates", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Settings.MainActionSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ActionDate")
                        .HasColumnType("date");

                    b.Property<long>("MaxNobleDistance")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("MinDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerNobleBudgets")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SkipNightSendings")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.ToTable("MainActionSettings", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Settings.ReconnaissanceSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MaxArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxPopulationInSourceVillage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MinArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MinDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinDistanceToFront")
                        .HasColumnType("integer");

                    b.Property<int>("MinSpyCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SkipNightSendings")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.ToTable("ReconnaissanceSettings", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.TargetGroups.TargetGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("BaseTemplateName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("VillageCoordinates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Waves")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("TargetGroups", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Templates.TargetTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Waves")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TargetTemplates", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Provider")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Users.UserSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_UserSessions_ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.NobleBudgetEntity", b =>
                {
                    b.HasOne("TWAction.Domain.Schedules.ScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.ScheduleEntity", b =>
                {
                    b.HasOne("TWAction.Domain.Users.UserEntity", null)
                        .WithMany("Schedules")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.Schedules.TroopsStateEntity", b =>
                {
                    b.HasOne("TWAction.Domain.Schedules.ScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.Settings.MainActionSettings", b =>
                {
                    b.HasOne("TWAction.Domain.Schedules.ScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TWAction.Domain.Settings.MainActionCatasSettings", "CatasSettings", b1 =>
                        {
                            b1.Property<Guid>("MainActionSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<long>("MaxOffUnits")
                                .HasColumnType("bigint");

                            b1.Property<long>("MinCatasNumber")
                                .HasColumnType("bigint");

                            b1.Property<long>("MinDistanceFromFront")
                                .HasColumnType("bigint");

                            b1.HasKey("MainActionSettingsId");

                            b1.ToTable("MainActionSettings");

                            b1.WithOwner()
                                .HasForeignKey("MainActionSettingsId");
                        });

                    b.OwnsOne("TWAction.Domain.Settings.MainActionFakeDeffSettings", "FakeDeffSettings", b1 =>
                        {
                            b1.Property<Guid>("MainActionSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<long>("MaxOffUnits")
                                .HasColumnType("bigint");

                            b1.Property<long>("MinDistanceFromFront")
                                .HasColumnType("bigint");

                            b1.HasKey("MainActionSettingsId");

                            b1.ToTable("MainActionSettings");

                            b1.WithOwner()
                                .HasForeignKey("MainActionSettingsId");
                        });

                    b.OwnsOne("TWAction.Domain.Settings.MainActionFakeOffSettings", "FakeOffSettings", b1 =>
                        {
                            b1.Property<Guid>("MainActionSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<long>("MinDistanceFromFront")
                                .HasColumnType("bigint");

                            b1.Property<long>("MinOffUnits")
                                .HasColumnType("bigint");

                            b1.HasKey("MainActionSettingsId");

                            b1.ToTable("MainActionSettings");

                            b1.WithOwner()
                                .HasForeignKey("MainActionSettingsId");
                        });

                    b.OwnsOne("TWAction.Domain.Settings.MainActionNobleSettings", "NobleSettings", b1 =>
                        {
                            b1.Property<Guid>("MainActionSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<long>("MaxOffUnitsForDefNoble")
                                .HasColumnType("bigint");

                            b1.Property<long>("MinDeffUnitsForDefNoble")
                                .HasColumnType("bigint");

                            b1.Property<long>("MinDistanceFromFront")
                                .HasColumnType("bigint");

                            b1.Property<long>("MinOffUnitsForFakeOffNoble")
                                .HasColumnType("bigint");

                            b1.Property<long>("MinOffUnitsForOffNoble")
                                .HasColumnType("bigint");

                            b1.HasKey("MainActionSettingsId");

                            b1.ToTable("MainActionSettings");

                            b1.WithOwner()
                                .HasForeignKey("MainActionSettingsId");
                        });

                    b.OwnsOne("TWAction.Domain.Settings.MainActionOffSettings", "OffSettings", b1 =>
                        {
                            b1.Property<Guid>("MainActionSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<long>("MinDistanceFromFront")
                                .HasColumnType("bigint");

                            b1.Property<long>("MinOffUnits")
                                .HasColumnType("bigint");

                            b1.HasKey("MainActionSettingsId");

                            b1.ToTable("MainActionSettings");

                            b1.WithOwner()
                                .HasForeignKey("MainActionSettingsId");
                        });

                    b.Navigation("CatasSettings")
                        .IsRequired();

                    b.Navigation("FakeDeffSettings")
                        .IsRequired();

                    b.Navigation("FakeOffSettings")
                        .IsRequired();

                    b.Navigation("NobleSettings")
                        .IsRequired();

                    b.Navigation("OffSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.Settings.ReconnaissanceSettings", b =>
                {
                    b.HasOne("TWAction.Domain.Schedules.ScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.TargetGroups.TargetGroup", b =>
                {
                    b.HasOne("TWAction.Domain.Schedules.ScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.Templates.TargetTemplate", b =>
                {
                    b.HasOne("TWAction.Domain.Users.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TWAction.Domain.Users.UserSessionEntity", b =>
                {
                    b.HasOne("TWAction.Domain.Users.UserEntity", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWAction.Domain.Users.UserEntity", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
