<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\TWAction.Infrastructure\TWAction.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\aspire\TwAction.ServiceDefaults\TwAction.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>62d271b2-862d-4c5d-8af2-09698ca76982</UserSecretsId>
  </PropertyGroup>

</Project>